export const roles =[
    "WAREHOUSE",
    "CAPTURIST",
    "INGENIO_ADMIN",
    "INGENIO_RECEPTION",
    "INGENIO_INSPECT",
    "CREDIT_COLLECTION",
    "INGENIO_DISTRIBUTION",
    "PRODUCER",
    "SUPERADMIN"
]