export interface IngenioDao {
    getIngenio(ingenioId: any): Promise<any>,
    getIngenioDetails(ingenioId: number): Promise<any>,
    deleteIngeniosById(ingenioId: string): Promise<any>,
    createIngenio(ingenio: any): Promise<any>,
    getIngenioByEmail(email: any): Promise<any>,
    getIngenioById(ingenioId: any): Promise<any>,
    getAllIngenios(params?: any): Promise<any>,
    getCountFormule(type: any, ingenioId: number, params?: any): Promise<any>,
    getDatatable(type: any, ingenioId: number, params?: any): Promise<any>,
    getListOfIngenios(): Promise<any>,
    geListOfOrdersByAlmacen(table: string): Promise<any>,
    getDataAplicated(ingenioId: any, params?: any): Promise<any>,
    geListOfOrderByIngenio(ingenioId: number): Promise<any>,
    getListOfZones(ingenioId: number, type: string): Promise<any>,
    getListOfClients(): Promise<any>,
}