export interface OrderDao {
    saveOrder(object: any): Promise<any>,
    getOrder(remissionnumber: number, ingenioid: number): Promise<any>,
    deleteOrderById(orderId: string): Promise<any>,
    getOrderById(orderId: any): Promise<any>,
    updateStatus(orderId: any, status: string): Promise<any>,
    getOrdersByStatus(params?: string): Promise<any>,
    orderById(orderId: number): Promise<any>,
    getOrdersWareHouse(): Promise<any>,
    getRemissionNumber(): Promise<any>,
    updateOrderByOrderIdAndIngenioId(orderId: string,ingenioId: string,objectRequest: any): Promise<any>,
    updateOrder(orderId: string,updateRequest: any): Promise<any>,
    updateRemission(remissionNumber: number): Promise<any>,
    getOrdersByIngenio(ingenioId: any,status: any): Promise<any>,
}